export interface ScsynthEntry {
  count: number;
  digest: string;
  start: number;
  features: {
    'r:centroid:mean': number,
    'r:centroid:std': number,
    'r:chroma:0': number,
    'r:chroma:1': number,
    'r:chroma:2': number,
    'r:chroma:3': number,
    'r:chroma:4': number,
    'r:chroma:5': number,
    'r:chroma:6': number,
    'r:chroma:7': number,
    'r:chroma:8': number,
    'r:chroma:9': number,
    'r:chroma:10': number,
    'r:chroma:11': number,
    'r:f0:mean': number,
    'r:f0:std': number,
    'r:flatness:mean': number,
    'r:flatness:std': number,
    'r:is_onset': number,
    'r:is_voiced': number,
    'r:mfcc:0': number,
    'r:mfcc:1': number,
    'r:mfcc:2': number,
    'r:mfcc:3': number,
    'r:mfcc:4': number,
    'r:mfcc:5': number,
    'r:mfcc:6': number,
    'r:mfcc:7': number,
    'r:mfcc:8': number,
    'r:mfcc:9': number,
    'r:mfcc:10': number,
    'r:mfcc:11': number,
    'r:mfcc:12': number,
    'r:peak:mean': number,
    'r:peak:std': number,
    'r:rms:mean': number,
    'r:rms:std': number,
    'r:rolloff:mean': number,
    'r:rolloff:std': number,
    'w:centroid:mean': number,
    'w:centroid:std': number,
    'w:chroma:0': number,
    'w:chroma:1': number,
    'w:chroma:2': number,
    'w:chroma:3': number,
    'w:chroma:4': number,
    'w:chroma:5': number,
    'w:chroma:6': number,
    'w:chroma:7': number,
    'w:chroma:8': number,
    'w:chroma:9': number,
    'w:chroma:10': number,
    'w:chroma:11': number,
    'w:f0:mean': number,
    'w:f0:std': number,
    'w:flatness:mean': number,
    'w:flatness:std': number,
    'w:is_onset': number,
    'w:is_voiced': number,
    'w:mfcc:0': number,
    'w:mfcc:1': number,
    'w:mfcc:2': number,
    'w:mfcc:3': number,
    'w:mfcc:4': number,
    'w:mfcc:5': number,
    'w:mfcc:6': number,
    'w:mfcc:7': number,
    'w:mfcc:8': number,
    'w:mfcc:9': number,
    'w:mfcc:10': number,
    'w:mfcc:11': number,
    'w:mfcc:12': number,
    'w:peak:mean': number,
    'w:peak:std': number,
    'w:rms:mean': number,
    'w:rms:std': number,
    'w:rolloff:mean': number,
    'w:rolloff:std': number,
  };
}

export type Axis = 'x' | 'y' | 'z';

export type Feature =
  | 'r:centroid:mean'
  | 'r:centroid:std'
  | 'r:chroma:0'
  | 'r:chroma:1'
  | 'r:chroma:2'
  | 'r:chroma:3'
  | 'r:chroma:4'
  | 'r:chroma:5'
  | 'r:chroma:6'
  | 'r:chroma:7'
  | 'r:chroma:8'
  | 'r:chroma:9'
  | 'r:chroma:10'
  | 'r:chroma:11'
  | 'r:f0:mean'
  | 'r:f0:std'
  | 'r:flatness:mean'
  | 'r:flatness:std'
  | 'r:is_onset'
  | 'r:is_voiced'
  | 'r:mfcc:0'
  | 'r:mfcc:1'
  | 'r:mfcc:2'
  | 'r:mfcc:3'
  | 'r:mfcc:4'
  | 'r:mfcc:5'
  | 'r:mfcc:6'
  | 'r:mfcc:7'
  | 'r:mfcc:8'
  | 'r:mfcc:9'
  | 'r:mfcc:10'
  | 'r:mfcc:11'
  | 'r:mfcc:12'
  | 'r:peak:mean'
  | 'r:peak:std'
  | 'r:rms:mean'
  | 'r:rms:std'
  | 'r:rolloff:mean'
  | 'r:rolloff:std'
  | 'w:centroid:mean'
  | 'w:centroid:std'
  | 'w:chroma:0'
  | 'w:chroma:1'
  | 'w:chroma:2'
  | 'w:chroma:3'
  | 'w:chroma:4'
  | 'w:chroma:5'
  | 'w:chroma:6'
  | 'w:chroma:7'
  | 'w:chroma:8'
  | 'w:chroma:9'
  | 'w:chroma:10'
  | 'w:chroma:11'
  | 'w:f0:mean'
  | 'w:f0:std'
  | 'w:flatness:mean'
  | 'w:flatness:std'
  | 'w:is_onset'
  | 'w:is_voiced'
  | 'w:mfcc:0'
  | 'w:mfcc:1'
  | 'w:mfcc:2'
  | 'w:mfcc:3'
  | 'w:mfcc:4'
  | 'w:mfcc:5'
  | 'w:mfcc:6'
  | 'w:mfcc:7'
  | 'w:mfcc:8'
  | 'w:mfcc:9'
  | 'w:mfcc:10'
  | 'w:mfcc:11'
  | 'w:mfcc:12'
  | 'w:peak:mean'
  | 'w:peak:std'
  | 'w:rms:mean'
  | 'w:rms:std'
  | 'w:rolloff:mean'
  | 'w:rolloff:std';

export interface SelectedAxes {
  x: Feature;
  y: Feature;
  z: Feature;
}
